### ISSUE TITLE
1.6 post-rebase tasks

### ISSUE THREAD

**Issue by sttts** [openshift/origin#13732]
## Blockers:
- [x] @soltysh ensure there are no fields with semantic differences between nil/[] or nil/{}, and if there are, they use alias nullable fields for protobuf and explicitly test round tripping (fuzzer tests won't catch the difference now)
- [x] switch storage version of HPA to autoscaling/v1 for 1.6
- [x] @sttts resurrect extensions/HPA API https://github.com/openshift/origin/pull/14021
- [x] potentially enable GarbageCollection if not having them leads to regressions
- [x] @liggitt The scopes on some types were being serialized incorrectly and this resulted in failing open. I've switched to manual conversions to move the rebase forward https://github.com/sttts/origin/pull/100#issue-224497853 (https://github.com/openshift/origin/pull/14132)
- [x] @enj Fix flake in TestEtcd2StoragePath https://github.com/openshift/origin/issues/14020 -> https://github.com/openshift/origin/issues/14051, https://github.com/openshift/origin/pull/14064#pullrequestreview-37683056

```
 --- FAIL: TestEtcd2StoragePath (34.55s)
        etcd_storage_path_test.go:960: failed to create stub for Pod from github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/api/v1:
n:""}, Status:"Failure", Message:"pods \"pod1\" is forbidden: service account etcdstoragepathtestnamespace/default was not found, retry af
        etcd_storage_path_test.go:960: failed to create stub for PolicyBinding from github.com/openshift/origin/pkg/authorization/api/v1:
:""}, Status:"Failure", Message:"policybindings.authorization.openshift.io \":default\" already exists", Reason:"AlreadyExists", Details:(
        etcd_storage_path_test.go:960: failed to create stub for Policy from github.com/openshift/origin/pkg/authorization/api/v1: &errors
tatus:"Failure", Message:"policies.authorization.openshift.io \"default\" already exists", Reason:"AlreadyExists", Details:(*v1.StatusDeta
        etcd.go:126: dumping etcd to "/tmp/openshift/test-integration/etcd-dump-TestEtcd2StoragePath.json"
```
- [ ] Re-enable broken e2e tests (compare https://github.com/openshift/origin/pull/13920/commits/8f4cf9b5f93a3ff48e2261e229888e63ed706320):
  - `Basic StatefulSet functionality \[StatefulSetBasic\] should provide basic identity` https://github.com/openshift/origin/pull/14052
  - `SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]`
- [x] oadm migrate image-references fails in CI https://github.com/openshift/origin/issues/13924 – #13924 is closed
- [x] @sttts disable rbac storage hook https://github.com/openshift/origin/pull/14002
- [x] verify preferred versions in API discovery (both order and preferredVersion) (~~autoscaling/v2alpha1 is marked as preferred, storage.k8s.io v1beta1 vs v1, etc~~) https://github.com/openshift/origin/pull/15160/files
- [x] @mfojtik  disable alpha APIs, @DirectXMan12 decide about hpa v2alpha1 https://github.com/openshift/origin/pull/13653#discussion_r114504779
- [x] @ncdc error cases for conversion in describe: https://github.com/openshift/origin/pull/13653#discussion_r112527115, https://github.com/openshift/origin/pull/13653#discussion_r112527425. PR https://github.com/openshift/origin/pull/13992
- [x] @ncdc nil-pointer check in describe https://github.com/openshift/origin/pull/13653#discussion_r112528342. PR #14034
- [x] Fix install + upgrade test https://github.com/openshift/origin/issues/13997
- [ ] Fix all-in-one networking https://github.com/openshift/origin/issues/13927#issuecomment-298112303 #14031 

## Further work:
- [x] @ncdc get lister-gen and informer-gen working with the new api groups. PR https://github.com/openshift/origin/pull/13982
- [ ] Dump etcd v3 contents in integration tests as we do for v2 https://github.com/openshift/origin/issues/14090#issuecomment-299940917  Issue already open: https://github.com/openshift/origin/issues/11837
- [ ] switch to generated clients / delete hand-written clients
- [ ] switch to external versions in controllers
- [ ] use secret shared informer in build/deploy/etc. controllers
- [ ] match apigroup package structure with upstream `pkg/apis/foo`
- [ ] get rid of sc.InternalDetermineEffectiveSecurityContext, as this goes away upstream (compare https://github.com/openshift/origin/pull/13653#pullrequestreview-32218155)
- [ ] convert the describer to use a versioned clientset where possible (eg. deployments, see `pkg/cmd/cli/describe/deployments.go`) https://github.com/openshift/origin/pull/13653/files/20348bb298cb570f49a78ff37c3ffec00255b2fb..dfd58523e1de61d9debdbd5af7aa9ac3e69111c9#diff-10042ecb2622b0122245db3a12c79f1a
- [ ] @ncdc: decide if we want to remove `/status` access for namespaced roles (https://github.com/openshift/origin/pull/13653/files/326fc9b4a9752f3d0d60fecf9e68017d5aa543f4..55dc4afdb6f775cfadd95c14161c1aaf153c7968#r111140469)
- [ ] @derekwaynecarr decide whether to enable taints
- [ ] remove setting NetworkPluginDir from pkg/cmd/server/kubernetes/node/node_config.go (cc @dcbw)
- [ ] re-enable etcd3, @liggitt to determine what's current re protobuf
- [ ] @liggitt replace originLongRunningRequestRE? with our own resource attributes check that tests for a buildconfigs resource and a instantiatebinary or imagestreamimports subresource? https://github.com/openshift/origin/pull/13653#discussion_r112748075
- [ ] @liggitt test for preferred versions in master_config_test.go https://github.com/openshift/origin/pull/13653#discussion_r112750833
- [ ] @liggitt refactor admission temp config files https://github.com/openshift/origin/pull/13653#discussion_r112754979
- [ ] upstream fix for double-counting quota for objects in more than one API group (plus tests) (and ensure admission quotas from both API groups)
- [ ] adopt kube rbac roles @deads2k @enj -> #14026 #14033

**Comment by mfojtik** [comment]
@sttts @enj @deads2k @smarterclayton for the kube alpha API's i found that we already have a way to disabled them: `kubernetesMasterConfig.disabledAPIGroupVersions`. I don't think we want to disable them by default, but if users want they can selectively disable. Is that enough?

**Comment by enj** [comment]
Why shouldn't they be disabled by default?  I would want all half done features to be off, and then I can turn them on if I understand the risks.

**Comment by mfojtik** [comment]
@enj if we start setting this now, it will probably break existing clusters? ;-)

**Comment by liggitt** [comment]
> if we start setting this now, it will probably break existing clusters? ;-)

we don't intentionally ship alpha types... what existing 1.6 clusters are you referring to?

**Comment by mfojtik** [comment]
@liggitt where we disabling them? the `kubernetesMasterConfig.disabledAPIGroupVersions` seems to be empty for me.

**Comment by deads2k** [comment]
> @liggitt where we disabling them? the kubernetesMasterConfig.disabledAPIGroupVersions seems to be empty for me.

As I recall, there is a default whitelist too.  Hardcoded.

**Comment by mfojtik** [comment]
@deads2k @liggitt @sttts anything critical missing from this list for 3.6?

**Comment by sttts** [comment]
@mfojtik the item about alpha versions is solved via https://github.com/openshift/origin/pull/14941 I guess. In there, settings.k8s.io is disabled.

**Comment by soltysh** [comment]
I think at this point all of the points are either handled or already outdated.
/close
