### ISSUE TITLE
post-rebase TODOs

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#14647]
- [x]  `UPSTREAM: <carry>: make namespace lifecycle access review aware` should be fixed by discovery.  If you can't get it, then it's not really stored. - https://github.com/openshift/origin/issues/15255
 - [x] find all the timeout increase carries.  Either make them configurable or bump them in kube. - https://github.com/openshift/origin/issues/15256
 - [x] `UPSTREAM: <carry>: Disable file locking in clientcmd` why would we do this.  Seems like it gets removed upstream or we deal with it. - https://github.com/openshift/origin/issues/15257
 - [x] `UPSTREAM: <carry>: match kube rbac setup in e2es with openshift kinds` drop when we move to RBAC authorizer - https://github.com/openshift/origin/issues/15258
 - [x] `UPSTREAM: 00000: disambiguate operation names for legacy discovery` move upstream - https://github.com/openshift/origin/issues/15259
 - [x] `UPSTREAM: <drop>: drop post 3.7 rebase. allows disabled aggregator` force aggregator always on and remove this - https://github.com/openshift/origin/issues/15260
 - [x] `UPSTREAM: <carry>: Add our types to kubectl get error` should be handled generically.  upstream needs to discover too - https://github.com/openshift/origin/issues/15261
 - [x] `UPSTREAM: <carry>: add kubelet timeouts` move upstream - #15256
 - [x] `UPSTREAM: <carry>: Allow overriding default generators for run` - just fix the upstream already - https://github.com/openshift/origin/issues/15262
 - [x] `UPSTREAM: <carry>: fix fifo resync, remove after FIFO is dead` fix this whereever it needs fixing - https://github.com/openshift/origin/issues/15263
 - [x] `UPSTREAM: <carry>: Fix to avoid REST API calls at log level 2.` - move upstream or drop it @aveshagarwal - https://github.com/openshift/origin/issues/15264
 - [x] `UPSTREAM: <drop>: Set the log level for iptables rule dump to 5` - move upstream or drop it (ben bennet) - https://github.com/openshift/origin/issues/15265
- [x] remove reflector.Run carry. - https://github.com/openshift/origin/issues/15266
- [x] bump  kube github.com/Azure/go-ansiterm - I think this is fixed when we move the registry out
- [x] bump kube github.com/Sirupsen/logrus - https://github.com/openshift/origin/issues/15295
- [x] bump kube github.com/cloudflare/cfssl/auth - https://github.com/openshift/origin/issues/15297
- [x] bump kube github.com/coreos/go-semver/semver - https://github.com/openshift/origin/issues/15299
- [x] bump kube github.com/docker/distribution/digest - I think this is fixed moving the registry out
- [x] bump kube github.com/google/certificate-transparency/go - https://github.com/openshift/origin/issues/15300
- [x] bump kube github.com/jonboulle/clockwork - https://github.com/openshift/origin/issues/15301
- [x] bump kube github.com/mailru/easyjson/buffer - https://github.com/openshift/origin/issues/15302
- [x] bump kube github.com/spf13/cobra - https://github.com/openshift/origin/issues/15303
- [x] bump kube golang.org/x/sys/unix - I think this is a transitive from registry again
- [x] bump kube golang.org/x/text/cases - https://github.com/openshift/origin/issues/15304
- [x] bump kube gopkg.in/yaml.v2 - https://github.com/openshift/origin/issues/15305
- [x] type assertions on all storage - https://github.com/openshift/origin/issues/15268
- [x] standardize GetAttrs - https://github.com/openshift/origin/issues/15267
- [x] must remove UPSTREAM: <carry>: allow to use * as a capability in Security Context - https://github.com/openshift/origin/issues/15273
- [x] remove UPSTREAM: <drop>: keep old pod available - https://github.com/openshift/origin/issues/15274
- [x] use upstream namespace lifecycle and remove project lifecycle one - https://github.com/openshift/origin/issues/15275
- [x] move non build admission plugins from admission package - https://github.com/openshift/origin/issues/15276
- [x] kill github.com/openshift/origin/pkg/client - https://github.com/openshift/origin/issues/15272
- [x] fix remaining controllers - https://github.com/openshift/origin/issues/15277
- [x] fix router metrics called out in pull.  haproxy.go and router.go MustRegister - https://github.com/openshift/origin/issues/15279
- [x] remove our shortcut expander. - https://github.com/openshift/origin/issues/15282
- [x] use factory for building resourcebuidlers - https://github.com/openshift/origin/issues/15278
- [x] remove NewProxyCommand - https://github.com/openshift/origin/issues/15286
- [x] remove sdn's GetNodeCondition - https://github.com/openshift/origin/issues/15283
- [x] make GetStandardPrinter respect the factory - https://github.com/openshift/origin/issues/15280
- [x] make upstream tests enforce ownerref restrictions in admission - https://github.com/openshift/origin/issues/15281
- [x] re-enable portworx - https://github.com/openshift/origin/issues/15269
- [x] add test to check configapi defaulting - https://github.com/openshift/origin/issues/15287
- [x] add integration tests for checking the ability to enable and disable versions - https://github.com/openshift/origin/issues/15285
- [x] gofmt version update - https://github.com/openshift/origin/issues/15270
- [x] wire-up the new `WithAudit` filter. Now we do only `WithLegacyAudit`. - https://github.com/openshift/origin/issues/15271
- [x] add new oc commands: 	"apiversions",	"clusterinfo",	"plugin",	"resize",	"rollingupdate", "run-container",	"update", - https://github.com/openshift/origin/issues/15288
   - looks like these are all deprecated (@sttts)
- [x] refactor SA token verifier for REST - https://github.com/openshift/origin/issues/15284
- [x] make master config clientgo client: privilegedLoopbackKubeClientsetClientGo - https://github.com/openshift/origin/issues/15293
- [x] simplify createAPIExtensionsConfig to streamline it.  no second copy for instance - https://github.com/openshift/origin/issues/15289
- [x] decide what to do about new admission plugins.  list in pkg/cmd/server/origin/admission/register.go - https://github.com/openshift/origin/issues/15290
- [x] reenable statefulset e2e tests: https://github.com/openshift/origin/issues/15252
- [x] reenable node port service e2e tests: https://github.com/openshift/origin/issues/15253
- [x] reenable schedulerpriorities e2e tests: https://github.com/openshift/origin/issues/15254
- [x] reenable `if _, err := url.Parse(o.RegistryUrlOverride); err != nil {` in `pkg/cmd/admin/prune/images.go` - https://github.com/openshift/origin/issues/15291
- [x] cleanup `InfraPersistentVolumeRecyclerControllerServiceAccountName` creation in `pkg/cmd/server/start/start_master.go` - https://github.com/openshift/origin/issues/15292
- [x] re-enable unidler: https://github.com/openshift/origin/issues/15101

```
Mismatch on github.com/coreos/etcd/alarm:
    Origin:  61fc123e7a8b14a0a258aa3f5c4159861b1ec2e7 (2017-06-22 09:47:21 -0700, discontinuous)
    K8s:    *20490caaf0dcd96bb4a95e40625559def8ef5b04 (2017-03-27 10:20:28 -0700, discontinuous)
    To check out newest:
    cd /home/deads/workspaces/openshift3/src/github.com/coreos/etcd/alarm && git checkout 61fc123e7a8b14a0a258aa3f5c4159861b1ec2e7

```

**Comment by smarterclayton** [comment]
- [ ] cAdvisor metrics are no longer shown kubernetes/kubernetes#48483

**Comment by liggitt** [comment]
bump coreos/etcd upstream to v3.2.1 - https://github.com/openshift/origin/issues/15322

**Comment by smarterclayton** [comment]
Seeing this in the logs on a real data set:

```
E0718 22:37:20.981215   74010 cacher.go:274] unexpected ListAndWatch error:
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215:
Failed to list *autoscaling.HorizontalPodAutoscaler: no kind
"HorizontalPodAutoscaler" is registered for version "extensions/v1beta1"
I0718 22:37:21.982476   74010 reflector.go:236] Listing and watching
*autoscaling.HorizontalPodAutoscaler from
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215
```

**Comment by liggitt** [comment]
did you run `oadm migrate`? should be written to autoscaling v1.

**Comment by smarterclayton** [comment]
Did we drop support for that in 1.6?  Because this is restore from a backup
onto 1.7

**Comment by liggitt** [comment]
dropped support in 1.7

**Comment by smarterclayton** [comment]
Ok, something I can test then

**Comment by smarterclayton** [comment]
Attach looks broken on Mac @fabianofranz 

```
$ oc run -it --attach --image="gcr.io/google_containers/hostexec:1.2" --restart=Never test
If you don't see a command prompt, try pressing enter.
```

I hit enter and nothing ever happens.  Did we fix something like this in upstream?

**Comment by smarterclayton** [comment]
Which is novel.

**Comment by kargakis** [comment]
@deads2k all TODOs seem ticked
