### ISSUE TITLE
3.8 rebase issue tracker

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#16065]
Collect known TODOs for 3.8 rebase:

- [x] drop ugorji drop commits
- [x] drop json-iter until it has soak time upstream
  - [ ] https://github.com/json-iterator/go/issues/191
- [x] change to include leading/trailing slashes in parsed subresource path param (affects WebHook#NewConnectOptions)
- [x] investigate why we need `LegacySchemeBuilder.Register(RegisterConversions)` in apps and image groups to make serialization test pass
- [ ] Verify and clean internal vendor dirs so that they contain up-to-date Godeps.json
- [ ] ~~Restore registry tests as registry moved to external repo (openshift/image-registry)~~ (migrated to https://github.com/openshift/origin/issues/17958)
- [ ] update docker inside pkg/build/vendor
- [ ] completly remove docker/engine-api, use docker/docker instead (in main origin part, not pkg/build/builder which has its own Godeps)
- [ ] update import-restrictions
- [ ] ~~fix 28c71b5f6f (UPSTREAM: onsi/ginkgo: 371: Allow tests to be modified), actually upstream it!~~ (migrated to https://github.com/openshift/origin/issues/17428)
- [ ] update all internal Godeps
- [ ] ~~update policies to cover the new resources (such as `apps/v1beta2`, etc.)~~ (migrated to https://github.com/openshift/origin/issues/17428)
- [ ] ~~test verifying k8s resources (including all possible versions) permissions~~ (migrated to https://github.com/openshift/origin/issues/17428)
- [ ] ~~drop `github.com/docker/engine-api` packages from S2I in favor of `github.com/docker/docker` only~~ moved to https://github.com/openshift/source-to-image/issues/833

**Comment by liggitt** [comment]
cc @mfojtik @soltysh for rebase

**Comment by liggitt** [comment]
@soltysh anything outstanding from this that needs a followup?

**Comment by soltysh** [comment]
@liggitt not sure what you mean by followup, there are still open issues here that needs addressing, and I'm currently working on it.

**Comment by soltysh** [comment]
The only ones that are left are godeps cleaning/munging but after talking with @deads2k I'm not going to. With all the rest either migrated to https://github.com/openshift/origin/issues/17428 or separate issues I'm closing this one.
