### ISSUE TITLE
3.9 rebase checklist

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#17428]
- [x] DefaultGarbageCollectionPolicy signature change (https://github.com/kubernetes/kubernetes/pull/55148)
- [ ] Test comparing origin and k8s admin/edit/view roles using [role aggregation](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/cluster-role-aggregation.md)
- [ ] ~~Run `kubectl` test-cmd tests against origin cluster (probably we could just use upstream test-cmd)~~ moved to card 
- [x] double check <drop>: skip scheduler configz error, drop once we run in a separate process and 
 <drop>: skip controller metric error, drop once we run in a separate process
- [ ] fix 28c71b5 (UPSTREAM: onsi/ginkgo: 371: Allow tests to be modified), actually upstream it!

**Comment by liggitt** [comment]
cc @openshift/sig-master

**Comment by soltysh** [comment]
/remove-lifecycle stale
@liggitt worth re-visiting while dealing with 1.10 rebase.
