### ISSUE TITLE
Tracking (even more) deps from origin on cli

### ISSUE THREAD

**Issue by juanvallejo** [openshift/origin#17630]
Followup to https://github.com/openshift/origin/pull/17309
Intent: https://docs.google.com/document/d/1mS-KRkU8zjCleBNi3WWhLtkH10hb8h4ajpFM743jnqg

Tracks dependencies on `kubectl` from anywhere outside of `pkg/oc`that need to be broken:

- [ ] pkg/config/cmd/cmd_test.go
- [ ] pkg/config/cmd/cmd.go
- [ ] pkg/templateservicebroker/cmd/server/start.go
- [ ] pkg/generate/app/templatelookup.go
- [ ] pkg/generate/app/errors.go
- [ ] pkg/api/graph/test/runtimeobject_nodebuilder.go
- [ ] pkg/api/validation/validation.go
- [ ] pkg/template/controller/templateinstance_controller.go
- [ ] pkg/authorization/reaper/cluster_role.go
- [ ] pkg/authorization/reaper/role.go
- [ ] pkg/build/cmd/reaper.go
- [ ] pkg/build/admission/jenkinsbootstrapper/admission.go
- [ ] pkg/cmd/server/start/start_node.go
- [ ] pkg/cmd/server/start/start_etcd.go
- [ ] pkg/cmd/server/start/start_allinone.go
- [ ] pkg/cmd/server/start/start_controllers.go
- [ ] pkg/cmd/server/start/start_api.go
- [ ] pkg/cmd/server/start/start_master.go
- [ ] pkg/cmd/server/admin/create_keypair.go
- [ ] pkg/cmd/server/admin/create_bootstrappolicy_file.go
- [ ] pkg/cmd/server/admin/create_kubeconfig.go
- [ ] pkg/cmd/server/admin/create_client.go
- [ ] pkg/cmd/server/admin/create_nodeconfig.go
- [ ] pkg/cmd/server/admin/encrypt.go
- [ ] pkg/cmd/server/admin/create_mastercerts.go
- [ ] pkg/cmd/server/admin/create_servercert.go
- [ ] pkg/cmd/server/admin/create_signercert.go
- [ ] pkg/cmd/server/admin/decrypt.go
- [ ] pkg/cmd/infra/router/template.go
- [ ] pkg/cmd/infra/router/f5.go
- [ ] pkg/cmd/infra/deployer/deployer.go
- [ ] pkg/cmd/infra/gitserver/gitserver.go
- [ ] pkg/cmd/infra/builder/builder.go
- [ ] pkg/cmd/templates/templater.go
- [ ] pkg/cmd/recycle/recycle.go
- [ ] pkg/cmd/openshift/openshift.go
- [ ] pkg/cmd/util/cmd_test.go
- [ ] pkg/cmd/util/term/terminal_writer.go
- [ ] pkg/cmd/util/sanity/cmd_sanity.go
- [ ] pkg/cmd/util/cmd.go
- [ ] pkg/user/reaper/user.go
- [ ] pkg/user/reaper/group.go
- [ ] pkg/project/registry/projectrequest/delegated/delegated.go
- [ ] pkg/route/generator/generate.go
- [ ] pkg/federation/kubefed/kubefed.go
- [ ] pkg/apps/cmd/scale.go
- [ ] pkg/apps/cmd/scale_test.go
- [ ] pkg/apps/cmd/status.go
- [ ] pkg/apps/cmd/test/support.go
- [ ] pkg/apps/cmd/generate.go
- [ ] pkg/apps/cmd/rollback.go
- [ ] pkg/apps/cmd/history.go
- [ ] pkg/apps/cmd/delete.go
- [ ] pkg/apps/strategy/recreate/recreate.go
- [ ] pkg/apps/strategy/rolling/rolling.go
- [ ] pkg/apps/strategy/rolling/rolling_test.go
- [ ] pkg/apps/registry/deploylog/rest.go

cc @deads2k @openshift/cli-review @liggitt
