### ISSUE TITLE
Umbrella Issue: Make openshift projects architecture independent

### ISSUE THREAD

**Issue by mkumatag** [openshift/origin#23385]
Umbrella Issue: Make Openshift projects architecture-neutral

**Goal**: Make all the build scripts architecture-neutral to build successfully on `non-amd64` platforms. There are few projects which are already architecture-neutral but not all the projects, so this issue is to track those missing projects and make them architecture-neutral.

List of projects need to be fixed:

- [x] https://github.com/openshift/release - openshift/release#4439

- [x] https://github.com/openshift/machine-config-operator - openshift/machine-config-operator#946, https://github.com/openshift/machine-config-operator/pull/1210

- [x] https://github.com/openshift/cluster-network-operator - openshift/cluster-network-operator#254
- [x] https://github.com/openshift/cluster-version-operator - openshift/cluster-version-operator#223
- [x] https://github.com/openshift/k8s-prometheus-adapter - openshift/k8s-prometheus-adapter#15
- [x] https://github.com/openshift/console-operator - openshift/console-operator#256

- [x] https://github.com/operator-framework/operator-marketplace - ~~operator-framework/operator-marketplace#225~~ , https://github.com/operator-framework/operator-marketplace/pull/236

- [x] https://github.com/openshift/service-catalog - openshift/service-catalog#58
- [x] https://github.com/openshift/sig-storage-local-static-provisioner - openshift/sig-storage-local-static-provisioner#12

- [x] jimmidyson/configmap-reload#34
- [x] openshift/etcd#15
~~- [ ] openshift/kubefed#12~~
- [x] openshift/kubefed-operator#42
- [x] openshift/openshift-tuned#19
- [x] openshift/sriov-network-operator#21
~~- [ ] openshift/cluster-api-provider-gcp#38~~
- [x] operator-framework/ghostunnel#9
- [x] kubernetes-sigs/node-feature-discovery#262
- [x] https://github.com/openshift/installer/pull/2297

**Comment by Pensu** [comment]
Have sent the PRs for following ones:

- https://github.com/openshift/cluster-network-operator - https://github.com/openshift/cluster-network-operator/pull/254
- https://github.com/openshift/cluster-version-operator - https://github.com/openshift/cluster-version-operator/pull/223
- https://github.com/openshift/console-operator - https://github.com/openshift/console-operator/pull/256
- https://github.com/operator-framework/operator-marketplace - https://github.com/operator-framework/operator-marketplace/pull/225
- https://github.com/openshift/service-catalog - https://github.com/openshift/service-catalog/pull/58

Will update the list while sending PRs for the rest.

**Comment by yselkowitz** [comment]
Here are some more PRs:

https://github.com/jimmidyson/configmap-reload/pull/34
https://github.com/openshift/etcd/pull/15
https://github.com/openshift/kubefed/pull/12
https://github.com/openshift/kubefed-operator/pull/42
https://github.com/openshift/openshift-tuned/pull/19
https://github.com/openshift/sriov-network-operator/pull/21

**Comment by yselkowitz** [comment]
Other issues for which we don't have patches yet:

* ghostunnel: vendor/golang.org/x/sys/unix needs fixes/rebase for at least ppc64le
* node-feature-discovery contains arch-specific code in source/cpu/cpu.go

**Comment by mkumatag** [comment]
> Other issues for which we don't have patches yet:
> 
> * ghostunnel: vendor/golang.org/x/sys/unix needs fixes/rebase for at least ppc64le
> * node-feature-discovery contains arch-specific code in source/cpu/cpu.go

@yselkowitz thanks for the PR, I have updated the first comment with all the PR you have submitted.
Will look into these issues as well.

**Comment by yselkowitz** [comment]
@mkumatag FYI I'm working on patches for node-feature-discovery.  Will update once PRs are filed.

**Comment by mkumatag** [comment]
> @mkumatag FYI I'm working on patches for node-feature-discovery. Will update once PRs are filed.

sure, hope that will take care cpu feature for power platform as well(in fact we can just return empty string array for cpu features for power platform as we don't get any flags when we run `lscpu` command)

**Comment by yselkowitz** [comment]
In general, we are trying to fix both IBM Power LE & Z in tandem.  PR filed:
https://github.com/kubernetes-sigs/node-feature-discovery/pull/262

**Comment by yselkowitz** [comment]
PR for ghostunnel:
https://github.com/operator-framework/ghostunnel/pull/9

**Comment by zvonkok** [comment]
How are the multi-arch images going to be managed, regarding a registry? Is the near time plan to support manifest lists or distinct repositories for each architecture? 

How one will make sure that the right arch-image lands on the right node?

**Comment by yselkowitz** [comment]
Red Hat uses manifest listing on its registry, and has since Power LE has been supported in various containers for ~1 year.  But I'm not sure how that's relevant to this topic.

**Comment by zvonkok** [comment]
By registry you mean the internal origin registry? Does quay.io has support
for manifest lists?

**Comment by yselkowitz** [comment]
Another PR:
https://github.com/openshift/cluster-api-provider-gcp/pull/38

Do you see any value to fixing the builds of AWS & Azure machine controllers?

**Comment by mkumatag** [comment]
> Do you see any value to fixing the builds of AWS & Azure machine controllers?

well, this can help when we have control plane installed on the non-amd64 platform and add AWS and Azure machines to the cluster, but not sure are there any such use-cases exist. At the moment those two can be a low priority

**Comment by mkumatag** [comment]
> By registry you mean the internal origin registry? Does quay.io has support for manifest lists?

As far as I know, openshift internal registry does not support fat manifest list, I remember reading quay.io started supporting fat manifest on an incremental basis. I'm not sure where the official openshift 4.x images have been pushed to quay or openshift cluster registry?

**Comment by yselkowitz** [comment]
Another PR:

https://github.com/openshift/cluster-image-registry-operator/pull/346

**Comment by adambkaplan** [comment]
@mkumatag you are correct - we explicitly don't support fat manifest lists in the internal registry. The primary reason is that manifest lists are not compatible with the imagestream API.

fyi @dmage

**Comment by mkumatag** [comment]
> @mkumatag you are correct - we explicitly don't support fat manifest lists in the internal registry. The primary reason is that manifest lists are not compatible with the imagestream API.
> 
> fyi @dmage

that's right, will have to fix imagestream, imagestreamtag APIs to accommodate registry changes for manifest list media type.

**Comment by clnperez** [comment]
Would we *have* to? Would it be possible to add that support first and then work it into the imagestream way of working? I'm not familiar with the openshift image-registry codebase, so, for all I know this would break something. Just brainstorming ways that we could keep from having teams who take advantage of manifest lists now re-do their workflows when moving to OpenShift.

**Comment by mkumatag** [comment]
> Would we _have_ to? Would it be possible to add that support first and then work it into the imagestream way of working? I'm not familiar with the openshift image-registry codebase, so, for all I know this would break something. Just brainstorming ways that we could keep from having teams who take advantage of manifest lists now re-do their workflows when moving to OpenShift.

As internally registry is tightly coupled with openshift and creates an object of type imagestream for every image, so not really sure whether we can really ignore that part. I don't see any easy solution, a customer may end up maintaining their own registry which supports manifest or use an external one.

**Comment by mkumatag** [comment]
All the mentioned PR are merged, hence closing this task now
