### ISSUE TITLE
Umbrella Issue: Build openshift test images for multi-arch

### ISSUE THREAD

**Issue by mkumatag** [openshift/origin#24091]
This task is to work with respect to build/publish container images required for openshift tests to work on multi-arch platforms(ppc64e, s390x)

- [ ] docker.io/mrogers950/origin-openldap-test:fedora29  - https://github.com/openshift/openldap.git
- [ ] docker.io/openshift/test-build-simples2i:latest - https://github.com/openshift/build-test-images/tree/master/simples2i
- [ ] docker.io/openshift/test-build-roots2i - https://github.com/openshift/build-test-images/tree/master/roots2i
- [ ] openshift/hello-openshift - https://github.com/openshift/origin/tree/master/examples/hello-openshift
- [ ] openshift/test-multicast - https://github.com/openshift/test-multicast.git
- [ ] openshift/origin-pod - https://github.com/openshift/images/tree/master/pod
