### ISSUE TITLE
Swagger Documentation Generation From Spec Is Not Automated

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#3828]
We need to fully automate the generation of Swagger-based documentation from the Swagger spec generated in OpenShift:

- [X] Generate Swagger spec automatically (#2660)
- [X] Verify that Swagger spec is up-to-date (#3827)
- [X] Verify that all necessary Swagger descriptions are up-to-date (#3832)
- [ ] Generate `adoc` from the Swagger spec automatically (partially done in #2660, table-of-contents and links still need to be automated)
- [ ] Move generated `adoc` (or `html` ? @smarterclayton ) into the `openshift-docs` repository

I need to understand the full pipeline better to implement the requisite changes. Seeking input from anyone consuming the spec or making docs. Specifically from @smarterclayton

**Comment by smarterclayton** [comment]
We have a helper in the other repo that copies the changes in - it's ok to
generate output in Origin and then have openshift-docs copy it in.

Also, one thing we need to do is resort the generated model objects in the
output in alphabetic or preferred order - right now they're essentially
random in the doc because they're in random order in the swagger spec
(although swagger has some stability).

On Wed, Jul 22, 2015 at 10:27 AM, Steve Kuznetsov <notifications@github.com>
wrote:

> We need to fully automate the generation of Swagger-based documentation
> from the Swagger spec generated in OpenShift:
>
>    -  Generate Swagger spec automatically (#2660
>    <https://github.com/openshift/origin/pull/2660>)
>    -  Verify that Swagger spec is up-to-date (#3827
>    <https://github.com/openshift/origin/pull/3827>)
>    -  Generate adoc from the Swagger spec automatically (partially done
>    in #2660 <https://github.com/openshift/origin/pull/2660>,
>    table-of-contents and links still need to be automated)
>    -  Move generated adoc (or html ? @smarterclayton
>    <https://github.com/smarterclayton> ) into the openshift-docs
>    repository
>
> I need to understand the full pipeline better to implement the requisite
> changes. Seeking input from anyone consuming the spec or making docs.
> Specifically from @smarterclayton <https://github.com/smarterclayton>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3828>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
We gen to adoc because openshift docs does the further conversion - it's
fine to stay adoc in our side.

On Wed, Jul 22, 2015 at 4:15 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> We have a helper in the other repo that copies the changes in - it's ok to
> generate output in Origin and then have openshift-docs copy it in.
>
> Also, one thing we need to do is resort the generated model objects in the
> output in alphabetic or preferred order - right now they're essentially
> random in the doc because they're in random order in the swagger spec
> (although swagger has some stability).
>
> On Wed, Jul 22, 2015 at 10:27 AM, Steve Kuznetsov <
> notifications@github.com> wrote:
>
>> We need to fully automate the generation of Swagger-based documentation
>> from the Swagger spec generated in OpenShift:
>>
>>    -  Generate Swagger spec automatically (#2660
>>    <https://github.com/openshift/origin/pull/2660>)
>>    -  Verify that Swagger spec is up-to-date (#3827
>>    <https://github.com/openshift/origin/pull/3827>)
>>    -  Generate adoc from the Swagger spec automatically (partially done
>>    in #2660 <https://github.com/openshift/origin/pull/2660>,
>>    table-of-contents and links still need to be automated)
>>    -  Move generated adoc (or html ? @smarterclayton
>>    <https://github.com/smarterclayton> ) into the openshift-docs
>>    repository
>>
>> I need to understand the full pipeline better to implement the requisite
>> changes. Seeking input from anyone consuming the spec or making docs.
>> Specifically from @smarterclayton <https://github.com/smarterclayton>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/issues/3828>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by stevekuznetsov** [comment]
@smarterclayton So, the things that remain necessary for the Swagger `adoc` generation are:
* table of contents
* sorting

I saw in the Kube `adoc` generation there was a script to fix links. Do we need to do that as well? It was on the process to turn the `adoc` into `html`, so maybe that should (does?) live in `openshift-docs`?

**Comment by stevekuznetsov** [comment]
FWIW It seems like the links inside of the `adoc` in the `openshift-docs` repo link to `CamelCase` headers and don't work as a result.

**Comment by smarterclayton** [comment]
Post process of the adoc (if we can't fix the upstream easily) is ok with
me.

On Wed, Jul 22, 2015 at 4:27 PM, Steve Kuznetsov <notifications@github.com>
wrote:

> FWIW It seems like the links inside of the adoc in the openshift-docs
> repo link to CamelCase headers and don't work as a result.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/issues/3828#issuecomment-123852446>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Swagger 2.0 is probably the most significant blocker at this point.  Going to close until then (the process is ok).
