### ISSUE TITLE
LDAP Sync TODO list

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#4851]
- [ ] delete orphaned groups from OpenShift records  (@stevekuznetsov /FTF)
- [ ] Active Directory schema (@deads2k)
- [ ] enhanced AD schema (FTF)
- [ ] blacklist {OpenShift,LDAP} groups from sync (@deads2k)
- [ ] extended test for: whitelist file from {OpenShift,LDAP} (@stevekuznetsov)
- [ ] extended test for: whitelist parameters for {OpenShift,LDAP} (@stevekuznetsov)
- [ ] extended test for:  user-defined mapping from LDAP uid to OpenShift uid (@stevekuznetsov)
- [ ] extended test for: secured LDAP ( also need to enhance LDAP image to support upgrade to TLS) (@stevekuznetsov)
- [ ] extended test for: pin OpenShift Group name for LDAP sync - sync OpenShift group to same UID (don't change annotation if LDAP group changes) (@deads2k)
- [ ] extended test for: delete orphaned groups (determine orphanage from OpenShift records)  (@stevekuznetsov /FTF)
- [ ] install openldap client on jenkins so that our sync jobs can mutate ldap at will with bash calls (@deads2k)

**Comment by deads2k** [comment]
@stevekuznetsov Schema1 works with an exposed config.  Once you get enough tests done for it, we can claim the trello card.

**Comment by deads2k** [comment]
"install openldap client" - https://github.com/openshift/vagrant-openshift/pull/336

**Comment by deads2k** [comment]
Need union group name mappings to allow user-defined if present and attributes otherwise.

Also, we need to make a label of the hostname on groups we sync.  Its not perfect, but its better than nothing.

We also need to add a custom `--label` flag to add custom labels.

**Comment by stevekuznetsov** [comment]
We need to find a way to mutate the host to be a label, previously there was the issue of formatting (labels can't have colons? I can't remember).

**Comment by deads2k** [comment]
> We need to find a way to mutate the host to be a label, previously there was the issue of formatting (labels can't have colons? I can't remember).

Yeah, we couldn't do host:port, but we need some kind of selector.  We'll do `host` by default (which should work) and we'll leave custom labels for people doing crazy things.

**Comment by lypht** [comment]
Happy New Year, all!  Is there a branch that is in sync with the Openshift Origin documentation?  Running `oadm groups sync --type=openshift --sync-config=foo.yml` as per [these instructions](https://docs.openshift.org/latest/install_config/syncing_groups_with_ldap.html#running-ldap-sync) throws **unknown command: sync** and **unknown flag: --type** errors respectively.  We have validated that the command fails on both a libvirt bin/cluster development build and a GCE BYO stack, both built from [openshift/openshift-ansible](https://github.com/openshift/openshift-ansible).

**Comment by stevekuznetsov** [comment]
@lypht Current Origin `HEAD` is in sync with the documentation, and the last changes for this command were made in commit https://github.com/stevekuznetsov/origin/commit/6eb1b3652c461588c9eed5ea3e9d74e994d722a7, merged fifteen days ago. Perhaps the build is picking up an older version? Does `openshift ex sync-groups` work in place of `oadm groups sync`?

**Comment by lypht** [comment]
Thanks, Steve.  It looks like what is being deployed through Ansible is from December 2nd.  Should I build from origin source to get these commits?

**Comment by stevekuznetsov** [comment]
The version from December 2nd should have LDAP group sync, but `oadm groups sync` is invoked with `openshift ex sync-groups`, but unless you upgrade to at least December 9th (https://github.com/openshift/origin/commit/d2c519988d829b2df749d9a4b022d0e0dd01326c), you won't have `oadm groups prune`. I'd suggest you use the latest version you can.

**Comment by lypht** [comment]
Thanks again.  If I run the upgrade playbook from BYO, will it pull the latest stable, or is this only for versioning if not on 1.1?

**Comment by stevekuznetsov** [comment]
I'm not certain about that, @sdodson could you please chime in?

**Comment by sdodson** [comment]
> Thanks again. If I run the upgrade playbook from BYO, will it pull the latest stable, or is this only for versioning if not on 1.1?

The playbooks, unless you specify that you want a containerized install, rely on RPMs for installation and those are only built for tagged releases. If you like you can add containerized=true and give that a shot but it's definitely a less tested path at this point.

https://github.com/openshift/openshift-ansible/blob/master/README_CONTAINERIZED_INSTALLATION.md documents containerized installation.

**Comment by lypht** [comment]
openshift ex sync-groups works.  Thanks again!

**Comment by stevekuznetsov** [comment]
@lypht glad to hear! Feel free to send other feedback or thoughts to me on GitHub or to our mailing list.

**Comment by pweil-** [comment]
nested groups doc https://docs.openshift.org/latest/install_config/syncing_groups_with_ldap.html#sync-ldap-nested-example

@stevekuznetsov close or send this @enj's way?

**Comment by stevekuznetsov** [comment]
@enj you are very welcome

**Comment by aneagoe** [comment]
I'm not really sure where a RFE would fit, but it's highly related to this topic. 
There doesn't seem to be a way to define multiple ldap URLs and the proposed way to handle redundancy is far from ideal (https://docs.openshift.com/container-platform/3.6/install_config/advanced_ldap_configuration/sssd_for_ldap_failover.html) since it requires configuration of additional infrastructure (two additional servers, httpd as proxy, integration of said servers with ldap and clustering to move a virtual IP between). Ideally, one should just be able to specify the additional URLs in the config and have openshift failover if the first one fails. Can this be integrated into this TODO list or where should I submit such request?

**Comment by enj** [comment]
@aneagoe I added it as a TODO item at the top, but you are welcome to submit an RFE to https://bugzilla.redhat.com.  Any changes to LDAP are low priority and are unlikely to be addressed at this time.

**Comment by rjhowe** [comment]
@aneagoe This was already proposed and denied keeping with the proposed way outlined in the doc link you provided. [Bug/RFE 1459046]( https://bugzilla.redhat.com/show_bug.cgi?id=1459046)

**Comment by stevekuznetsov** [comment]
RIP :rose:

**Comment by enj** [comment]
/unassign

@stlaz @sttts @mfojtik
