### ISSUE TITLE
Rebase checklist

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#5684]
Holding location for issues we'll need to address in the next rebase:

- [ ] 16221 upstream changed KindToResource handling of kinds ending in "s", so we'll need to carry an exception for "securitycontextconstraints" (both in go and in the UI/Eclipse clients)
- [ ] 16082 upstream changed negotiate behavior, need to ensure our negotiate still functions correctly
- [ ] 14881 upstream changed deltaFIFO behavior in a way that breaks the build controller. see https://github.com/openshift/origin/pull/5339#discussion_r42921986
