### ISSUE TITLE
Finalize Kube items 3.2

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#6766]
Placeholder to track upstream pulls that need to be included in 3.2.
Link to upstream pulls with a comment.
After rebases are completed, we'll look at which ones need to be cherry-picked and track them here.

Upstream release branch cherry pick candidates: 
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Acherrypick-candidate+milestone%3Av1.2+

Other items:

- [x] Carry for SCC describer: #7127 (fork pull: openshift/kubernetes#5)
- [ ] Track the resolution of ~~kubernetes/kubernetes#22025~~ kubernetes/kubernetes#20497
- [ ] Doc upgrading a node involves draining or restarting containers (because of cgroup changes, and because of https://github.com/kubernetes/kubernetes/issues/23104)
- [ ] Fix for https://github.com/kubernetes/kubernetes/pull/21741

In master upstream:

- [x] https://github.com/kubernetes/kubernetes/pull/23003 (Origin PR https://github.com/openshift/origin/pull/8016) fixes https://github.com/openshift/origin/issues/7694
- [x] kubernetes/kubernetes#22634 (Origin PR https://github.com/openshift/origin/pull/7829) fixes https://github.com/openshift/origin/issues/7811
- [x] Origin PR https://github.com/openshift/origin/pull/8100 (upstream PR https://github.com/kubernetes/kubernetes/pull/23078 and https://github.com/kubernetes/kubernetes/pull/23548)

Proposed for v1.2.3:

- [x] https://github.com/kubernetes/kubernetes/pull/24208 (origin PR #8514)
- [x] kubernetes/kubernetes#23435 (origin PR #8501)

In v1.2.2:

- [x] https://github.com/kubernetes/kubernetes/pull/23943 (fix volume GetCloudProvider, origin PR https://github.com/openshift/origin/pull/8492)
- [x] https://github.com/kubernetes/kubernetes/pull/23935 (make configmap volume readable, origin PR #8411)
- [x] https://github.com/kubernetes/kubernetes/pull/23934/ (fix daemonset pod shouldRun, add events for daemonset failures, origin PR https://github.com/openshift/origin/pull/8492)
- [x] kubernetes/kubernetes#23746 (Origin PR https://github.com/openshift/origin/pull/8378)

In v1.2.1:

- [x] https://github.com/kubernetes/kubernetes/pull/23586 (validate daemonsets don't have empty selectors, Origin PR https://github.com/openshift/origin/pull/8308)
- [x] https://github.com/kubernetes/kubernetes/pull/23145 (Origin PR https://github.com/openshift/origin/pull/8098) fixes issue https://github.com/openshift/origin/issues/6435
- [x] https://github.com/kubernetes/kubernetes/pull/23035 (race causing endpoints flush during restart, origin PR https://github.com/openshift/origin/pull/8277)
- [x] https://github.com/kubernetes/kubernetes/pull/23143 (cpu limit >= 10m, origin PR https://github.com/openshift/origin/pull/8277)
- [x] https://github.com/kubernetes/kubernetes/pull/23141 (kubelet update all pods at once, origin PR https://github.com/openshift/origin/pull/8277)
- [x] https://github.com/kubernetes/kubernetes/pull/23019 (rate limit GCE cloudprovider, origin PR https://github.com/openshift/origin/pull/8277)?
- [x] https://github.com/kubernetes/kubernetes/pull/23325 (fix hairpin mode, origin PR https://github.com/openshift/origin/pull/8277)
- [x] https://github.com/kubernetes/kubernetes/pull/23457 (remove usage metric on hostpath volume, origin PR https://github.com/openshift/origin/pull/8277)
- [x] https://github.com/kubernetes/kubernetes/pull/23456 (don't sync daemonsets with no selector, origin PR https://github.com/openshift/origin/pull/8277)

In v1.2.0 (Origin PR https://github.com/openshift/origin/pull/8072):

- [x] kubernetes/kubernetes#22847 for API change
- [x] https://github.com/kubernetes/kubernetes/pull/22791
- [x] https://github.com/kubernetes/kubernetes/pull/22942 helps with bz#1316095
- [x] https://github.com/kubernetes/kubernetes/pull/22803 (contains google/cadvisor#1152 cAdvisor hangs for 20s on startup when not on GCE/AWS.  This means that the kubelet also hangs for 20s on startup.)
- [x] https://github.com/kubernetes/kubernetes/pull/23020 (contains google/cadvisor#1158 to reduce high cpu load from collecting network stats), part of a round of 1.2 cherrypicks here https://github.com/kubernetes/kubernetes/pull/23024
- [x] Add user-agent default for discovery client: kubernetes/kubernetes#22746 (already picked)

In the v1.2-beta.1 rebase (Origin PR https://github.com/openshift/origin/pull/7975):
- [x] cache resizing kubernetes/kubernetes#19783
- [x] kubecontainer.Cache kubernetes/kubernetes#19850 , there a number of fixes that are associated with this PR set so I'm hoping next rebase is after this merge.
- [x] Scheduler predicate to cap AWS EBS vols kubernetes/kubernetes#19880
- [x] kubernetes/kubernetes#19739 Cadvisor update, fixes goroutine leak, jitter on housekeeping, and modifications necessary for metrics api. @ncdc do you have coverage of the metrics api changes?
- [x] There will probably need to be another cadvisor bump too. It's currently part of kubernetes/kubernetes#19354. It has fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1300570.
- [x] kubernetes/kubernetes#19970 Fixes namescoping in a bunch of cachers.
- [x] Use Openstack os-ext-ips extension to qualify IP address types kubernetes/kubernetes#18829 For bug https://bugzilla.redhat.com/show_bug.cgi?id=1303085
- [x] Follow-up from 19354: kubernetes/kubernetes#20395
- [x] E2E libraryzation - kubernetes/kubernetes#19624 for #6541 /cc @jayunit100
- [x] AWS EBS Volume Limit Scheduler Predicate - kubernetes/kubernetes#19880
- [x] Quantity can lose formatting: kubernetes/kubernetes#20505
- [x] Make container runtime's cgroup configurable kubernetes/kubernetes#20687 Fixes bootstrapping of the kubelet on systemd to no longer move docker daemon.
- [x] namespace deletion improvements: kubernetes/kubernetes#20076 (for #7166)
- [x] nice to have (allows running oc in pods without any manual setup): kubernetes/kubernetes#21095
- [x] No-op changes: kubernetes/kubernetes#20897
- [x] Don't rate limit watches: kubernetes/kubernetes#21104 Still pending, but the root of several issues...
- [x] kubernetes/kubernetes#17493
- [x] kubernetes/kubernetes#18010
- [x] nice to have: kubernetes/kubernetes#20726
- [x] kubernetes/kubernetes#21179
- [x] kubernetes/kubernetes#21266 needed for #6804
- [x] kubernetes/kubernetes#21335 is needed for #7329
- [x] ~~kubernetes/kubernetes#21324~~ kubernetes/kubernetes#21398 is needed for https://bugzilla.redhat.com/show_bug.cgi?id=1286116
- [x] kubernetes/kubernetes#21340 for namespace deletion races
- [x] kubernetes/kubernetes#21273 for fixing deployments against unready apps EDIT: Already merged in Origin (#7307)
- [x] change kubelet defaults: kubernetes/kubernetes#21361
- [x] kubernetes/kubernetes#21286 handles some types of Docker cfg secrets from being selected by the keyring.
- [x] kubernetes/kubernetes#21470 needed for #7401
- [x] Fix type for DaemonSet informer in node controller: kubernetes/kubernetes#21496
- [x] kubernetes/kubernetes#21341 for enhancing the dc describer EDIT: Already merged in Origin (#7354)
- [x] kubernetes/kubernetes#21286
- [x] kubernetes/kubernetes#21175 <kubernetes/kubernetes#21175 (comment)> because it's API incompatible with 3.1
- [x] kubernetes/kubernetes#21671 for the pod describer EDIT: Already merged in Origin (#7516)
- [x] Fix duplicate updates on pod delete: kubernetes/kubernetes#21732 This can flood channels in kubelet when doing bulk pod deletion.  EDIT(ncdc): THIS WAS REVERTED!  EDIT2(ncdc): here's the replacement: kubernetes/kubernetes#21959
- [x] Fix LimitRanger LRU cach: kubernetes/kubernetes#21788
- [x] Perf improvement for quota replenishment: kubernetes/kubernetes#22445
- [x] Force pod status update in kubelet if deletionTimestamp is set: kubernetes/kubernetes#22483
- [x] kubernetes/kubernetes#22516 (only the first commit is enough - Origin PR: #7796)
- [x] kubernetes/kubernetes#22526 (Origin PR: #7828)
- [x] Quota replenishment perf: kubernetes/kubernetes#22628
- [x] fix for bz#1311868: "No tags for dynamic provisioned volume in AWS": kubernetes/kubernetes#20900
- [x] fix for bz#1311312 "AWS and GCE Dynamic provisioners do not work": kubernetes/kubernetes#21738
- [x] Keep an eye on kubernetes/kubernetes#22607. We'll most likely want it, assuming it merges.
- [x] Kubelet stats is wrong on systemd kubernetes/kubernetes#22656
- [x] kubernetes/kubernetes#22769 API changes to scale subresources
- [x] kubernetes/kubernetes#22724 API changes to scale subresources
- [x] kubernetes/kubernetes#22758 API change to replicaset:
- [x] Loosen LimitRange validation @aveshagarwal kubernetes/kubernetes#22766 This is not targeted 1.2, but is just a small change to validation.
- [x] If kubernetes/kubernetes#22853 merges, then we'll need to pick it to get consistent client tool capability.
- [x] kubernetes/kubernetes#22865 secrets in envvars don't obey SA limits
- [x] kubernetes/kubernetes#22802 ensures that spdystream goroutines are cleaned up when the exec/attach/portforward spdy connection is closed. Requires kubernetes/kubernetes#22804 to function 100% properly.
- [x] Nice to have so we don't get log spam google/cadvisor#1122

Not in 1.2:
- [ ] ~~ThirdPartyResources is still targeted for 1.2 and is big enough to impact whether future patches apply cleanly: kubernetes/kubernetes#18835~~ moved to 1.3
- [ ] ~~Adapt to kubernetes/kubernetes#20688~~ - opened https://github.com/openshift/origin/issues/8179 to track
- [ ] ~~kubernetes/kubernetes#21373~~ (Origin PR https://github.com/openshift/origin/pull/8062, reverted in https://github.com/openshift/origin/pull/8197 because of https://bugzilla.redhat.com/show_bug.cgi?id=1319439 until google/cadvisor#1171 is picked up)
- [ ] kubernetes/kubernetes#20918 fixes a regression in oc edit to handle lists.
- [ ] ~~kubernetes/kubernetes#23213 (origin PR #8194) - needed before next rebase~~

**Comment by liggitt** [comment]
From https://github.com/openshift/origin/issues/6881#issuecomment-176544010
- cache resizing https://github.com/kubernetes/kubernetes/pull/19783
- kubecontainer.Cache https://github.com/kubernetes/kubernetes/pull/19850 , there a number of fixes that are associated with this PR set so I'm hoping next rebase is after this merge. 
- Scheduler predicate to cap AWS EBS vols https://github.com/kubernetes/kubernetes/pull/19880

**Comment by ncdc** [comment]
Always pull images: https://github.com/kubernetes/kubernetes/pull/18909

**Comment by timothysc** [comment]
- https://github.com/kubernetes/kubernetes/pull/19739 Cadvisor update, fixes goroutine leak, jitter on housekeeping, and modifications necessary for metrics api.  @ncdc do you have coverage of the metrics api changes?

**Comment by ncdc** [comment]
There will probably need to be another cadvisor bump too. It's currently part of https://github.com/kubernetes/kubernetes/pull/19354. It has fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1300570.

@timothysc which metrics changes are you referring to? We aren't going to need cadvisor changes for custom metrics until 3.3.

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/19970

Fixes namescoping in a bunch of cachers.

**Comment by ncdc** [comment]
Use Openstack os-ext-ips extension to qualify IP address types https://github.com/kubernetes/kubernetes/pull/18829

For bug https://bugzilla.redhat.com/show_bug.cgi?id=1303085

**Comment by ncdc** [comment]
Follow-up from 19354: https://github.com/kubernetes/kubernetes/pull/20395

**Comment by timothysc** [comment]
E2E libraryzation - https://github.com/kubernetes/kubernetes/pull/19624 for https://github.com/openshift/origin/pull/6541  /cc @jayunit100

**Comment by DirectXMan12** [comment]
AWS EBS Volume Limit Scheduler Predicate - kubernetes/kubernetes#19880

**Comment by jayunit100** [comment]
E2E libraryzation also would need https://github.com/kubernetes/kubernetes/pull/19778 #7049

**Comment by derekwaynecarr** [comment]
Quantity can lose formatting: https://github.com/kubernetes/kubernetes/pull/20505

**Comment by pweil-** [comment]
Carry for SCC describer: https://github.com/openshift/origin/pull/7127 (fork pull: https://github.com/openshift/kubernetes/pull/5)

**Comment by timothysc** [comment]
@pweil - if there is a final rebase I believe you can drop most of the items I have listed above.

**Comment by derekwaynecarr** [comment]
Make container runtime's cgroup configurable
https://github.com/kubernetes/kubernetes/pull/20687

Fixes bootstrapping of the kubelet on systemd to no longer move docker daemon.

**Comment by pweil-** [comment]
namespace deletion improvements: https://github.com/kubernetes/kubernetes/pull/20076 (for https://github.com/openshift/origin/issues/7166)

**Comment by liggitt** [comment]
nice to have (allows running `oc` in pods without any manual setup): https://github.com/kubernetes/kubernetes/pull/21095

**Comment by smarterclayton** [comment]
No-op changes: https://github.com/kubernetes/kubernetes/pull/20897

**Comment by timothysc** [comment]
Don't rate limit watches: https://github.com/kubernetes/kubernetes/pull/21104

Still pending, but the root of several issues...

**Comment by jsafrane** [comment]
Fixes for BZ#1305546: https://github.com/openshift/origin/pull/7258 https://github.com/openshift/origin/pull/7260

**Comment by liggitt** [comment]
subresource proxy for nodes/services:
https://github.com/kubernetes/kubernetes/pull/17493
https://github.com/kubernetes/kubernetes/pull/18010

**Comment by timothysc** [comment]
nice to have: https://github.com/kubernetes/kubernetes/pull/20726

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/21179

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/21266 needed for https://github.com/openshift/origin/issues/6804

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/21335 is needed for https://github.com/openshift/origin/issues/7329

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/21324 is needed for https://bugzilla.redhat.com/show_bug.cgi?id=1286116

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/21340 for namespace deletion races

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/21273 for fixing deployments against unready apps

**Comment by timothysc** [comment]
change kubelet defaults: https://github.com/kubernetes/kubernetes/pull/21361

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/20918 fixes a regression in `oc edit` to handle lists.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/21286 handles some types of
Docker cfg secrets from being selected by the keyring.

**Comment by deads2k** [comment]
kubernetes/kubernetes#21470 needed for https://github.com/openshift/origin/issues/7401

**Comment by ncdc** [comment]
Fix type for DaemonSet informer in node controller: https://github.com/kubernetes/kubernetes/pull/21496

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/21341 for enhancing the dc describer

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/21286

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/21175
<https://github.com/kubernetes/kubernetes/pull/21175#issuecomment-186614128>
because
it's API incompatible with 3.1

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/21671 for the pod describer

**Comment by jsafrane** [comment]
https://github.com/openshift/origin/pull/7459 to fix blocker BZ#1308588

**Comment by derekwaynecarr** [comment]
Fix duplicate updates on pod delete: https://github.com/kubernetes/kubernetes/pull/21732

This can flood channels in kubelet when doing bulk pod deletion.

**Comment by ncdc** [comment]
Nice to have so we don't get log spam https://github.com/google/cadvisor/pull/1122

**Comment by derekwaynecarr** [comment]
Fix LimitRanger LRU cache:
https://github.com/kubernetes/kubernetes/pull/21788

**Comment by smarterclayton** [comment]
We need to track the resolution of kubernetes/kubernetes#22025

**Comment by smarterclayton** [comment]
Adapt to https://github.com/kubernetes/kubernetes/pull/20688

**Comment by derekwaynecarr** [comment]
Perf improvement for quota replenishment:
https://github.com/kubernetes/kubernetes/pull/22445

**Comment by ncdc** [comment]
Force pod status update in kubelet if deletionTimestamp is set: https://github.com/kubernetes/kubernetes/pull/22483

**Comment by kargakis** [comment]
Deployment bug fixes:
https://github.com/kubernetes/kubernetes/pull/22516 (only the first commit)
https://github.com/kubernetes/kubernetes/pull/22526

oc edit fix:
https://github.com/kubernetes/kubernetes/pull/22634

**Comment by derekwaynecarr** [comment]
Quota replenishment perf:
https://github.com/kubernetes/kubernetes/pull/22628

**Comment by jsafrane** [comment]
fix for bz#1311868:  "No tags for dynamic provisioned volume in AWS":  https://github.com/kubernetes/kubernetes/pull/20900

**Comment by jsafrane** [comment]
fix for bz#1311312 "AWS and GCE Dynamic provisioners do not work": https://github.com/kubernetes/kubernetes/pull/21738

**Comment by ncdc** [comment]
Keep an eye on https://github.com/kubernetes/kubernetes/pull/22607. We'll most likely want it, assuming it merges.

**Comment by derekwaynecarr** [comment]
Kubelet stats is wrong on systemd
https://github.com/kubernetes/kubernetes/pull/22656

**Comment by ncdc** [comment]
Add user-agent default for discovery client: https://github.com/kubernetes/kubernetes/pull/22746

**Comment by derekwaynecarr** [comment]
In case this does not make kube 1.2, we should carry the following for cadvisor:

https://github.com/google/cadvisor/pull/1152

cAdvisor hangs for 20s on startup when not on GCE/AWS.  

This means that the kubelet also hangs for 20s on startup.

**Comment by liggitt** [comment]
API changes to scale subresources
https://github.com/kubernetes/kubernetes/pull/22769
https://github.com/kubernetes/kubernetes/pull/22724

API change to replicaset:
https://github.com/kubernetes/kubernetes/pull/22758/

**Comment by deads2k** [comment]
ThirdPartyResources is still targeted for 1.2 and is big enough to impact whether future patches apply cleanly: https://github.com/kubernetes/kubernetes/pull/18835

**Comment by derekwaynecarr** [comment]
Loosen LimitRange validation @aveshagarwal 

https://github.com/kubernetes/kubernetes/pull/22766

This is not targeted 1.2, but is just a small change to validation.

**Comment by deads2k** [comment]
If https://github.com/kubernetes/kubernetes/pull/22853 merges, then we'll need to pick it to get consistent client tool capability.

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/22865 secrets in envvars don't obey SA limits

**Comment by ncdc** [comment]
https://github.com/kubernetes/kubernetes/pull/22802 ensures that spdystream goroutines are cleaned up when the exec/attach/portforward spdy connection is closed. Requires https://github.com/kubernetes/kubernetes/pull/22804 to function 100% properly.

**Comment by ncdc** [comment]
https://github.com/google/cadvisor/pull/1158 to reduce high cpu load from collecting network stats

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/22847 for API change

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/21373 would help integration with manageiq and is contained.  I'd like to pick it even though kube 1.2 will not have it.  Testing has been discussed.

**Comment by eparis** [comment]
^^^^^^^^^^^^^^^^^^^^^ everything above this point it not in the checklist ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by kargakis** [comment]
oc edit fix: https://github.com/kubernetes/kubernetes/pull/22634. related issue: https://github.com/openshift/origin/issues/7811

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/23003 fixes https://github.com/openshift/origin/issues/7694

**Comment by jsafrane** [comment]
https://github.com/kubernetes/kubernetes/pull/22942 helps with bz#1316095

**Comment by ncdc** [comment]
https://github.com/kubernetes/kubernetes/pull/23020 (contains cadvisor 1158), part of a round of 1.2 cherrypicks here https://github.com/kubernetes/kubernetes/pull/23024

**Comment by liggitt** [comment]
^^^^^^^^^^^^^^^^^^^^^ everything above this point it now in the checklist ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by childsb** [comment]
https://github.com/kubernetes/kubernetes/pull/21758

**Comment by liggitt** [comment]
anything merged to kube master prior to 3/11/2016 is already in origin

**Comment by childsb** [comment]
https://github.com/kubernetes/kubernetes/pull/21738

**Comment by smarterclayton** [comment]
Potentially https://github.com/kubernetes/kubernetes/pull/23035 -
controller failover can flush the endpoints list (make them zero)

**Comment by swagiaal** [comment]
https://github.com/openshift/origin/pull/8100
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1310587

**Comment by derekwaynecarr** [comment]
cpu limits must be >= 10m

https://github.com/kubernetes/kubernetes/pull/23143

**Comment by pweil-** [comment]
provide best effort generation for struct fields

https://github.com/kubernetes/kubernetes/pull/23213

pick https://github.com/openshift/origin/pull/8194

**Comment by liggitt** [comment]
^^^^ everything above this point it now in the checklist ^^^^

**Comment by smarterclayton** [comment]
Need to be aware of https://github.com/kubernetes/kubernetes/pull/21741 - I'm hitting this on a daily basis

**Comment by derekwaynecarr** [comment]
Pods stuck in terminating state if the registry is unavailable:

https://github.com/kubernetes/kubernetes/pull/23746

**Comment by liggitt** [comment]
^^^^ everything above this point it now in the checklist ^^^^

**Comment by jsafrane** [comment]
Containerized OpenShift should be able to mount volumes

https://github.com/kubernetes/kubernetes/pull/23435
https://bugzilla.redhat.com/show_bug.cgi?id=1313210

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/24208/

**Comment by liggitt** [comment]
^^^^ everything above this point it now in the checklist ^^^^

**Comment by liggitt** [comment]
closing, will track items individually from here on
