### ISSUE TITLE
Rebase TODOs

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6906]
Just a scratchpad for me to keep track of my current problems.

 - [x] move configapi to its own internal group, with a different external group for serialization or re-separate the schemes https://github.com/openshift/origin/issues/7116
 - [x] `ResolveResource` needs to return a GVR https://github.com/openshift/origin/issues/7117
 - [x] `field.Required` needs details everywhere https://github.com/openshift/origin/issues/7118
 - [x] disabled `ValidateKubeletExtendedArguments`, `ValidateAPIServerExtendedArguments` and `ValidateControllerExtendedArguments`
 - [x] `cmd/tag.go` `func determineSourceKind(f *clientcmd.Factory, input string) string {`
 - [x] fix ConvertToVersion https://github.com/openshift/origin/issues/7119
 - [x] fix conversion.Meta https://github.com/openshift/origin/issues/7119
 - [x] fix union restmapper https://github.com/openshift/origin/issues/7119
 - [x] type the restmapper errors https://github.com/openshift/origin/issues/7119
 - [x] `--output-version` needs to handle multiple groups https://github.com/openshift/origin/issues/7119
 - [x] make our kube fork able to generate v1beta3 https://github.com/openshift/origin/issues/7120
 - [ ] fix the policy_test.go package and TestFieldSelectorConversions There's a trip dependency somewhere.
 - [ ] enable: 	```"PersistentVolumeLabel", // do we want this? disable by default
	"AlwaysPullImages",      // do we want this? disable by default```
 - [ ] `expandResourceShortcut` should use a static map
 - [ ] check the etcdclient retry behavior we use checkretry for before

Things we need in the transitive tool:
Just a spot to note things that would be handy:
 1. multiple sorts, so I can get "openshift deps that are newer"
 1.  ```bash
cd $GOPATH/src/<godep name>
git checkout master
git checkout -b openshift-level
git reset --hard <openshift-level>
```
   puts the godep into the right state for a save
 1. It's possible to look for `UPSTREAM: ` commits to things under the godep path to note whether we've patched them.
 1. special-case cadvisor to always take the kube level
 1. The transitive dependency check should be less transitive.  I only want separate bumps for things that openshift directly depends on.

**Comment by kargakis** [comment]
@deads2k are all items in this list done?

**Comment by deads2k** [comment]
> @deads2k are all items in this list done?

Yeah, I think we're good.
