### ISSUE TITLE
1.3 upstream picks

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9790]
PRs that should be included in the 1.3 release:

## kube pulls

Description|Upstream PR|Upstream Merge|Origin PR|Status
-----------|-------------|-----------------|----------|------
Allow specifying secret data using strings |kubernetes/kubernetes#28263|7/1/16 3:28:56 AM|#9663|Merged
kubectl: don't display empty list when trying to get a single resource that isn't found|kubernetes/kubernetes#28294|7/1/16 4:40:46 PM|#10247|Merged
Add MinReadySeconds to rolling updater|kubernetes/kubernetes#28111|7/1/16 10:21:16 PM|#9852|Merged
Add ForgetPod to SchedulerCache|kubernetes/kubernetes#28886|7/14/16 8:30:23 AM|#10247|Merged
node controller allocation changes|kubernetes/kubernetes#29063|7/16/16 8:27:56 PM|#10247|Merged
docker_manager: Correct determineContainerIP args|kubernetes/kubernetes#29171|7/20/16 3:26:37 PM|#10141|Merged
Kubelet: Set PruneChildren when removing image|kubernetes/kubernetes#29246|7/20/16 3:59:54 PM|#10247|Merged
node controller allocation changes part 2|kubernetes/kubernetes#29576|7/27/16 3:59 AM|#10247|Merged
Add Apps() and PetSet client to client/unversioned|kubernetes/kubernetes#29655|7/28/16 4:54:16 PM|#9972|Merged
Allow PVs to specify supplemental GIDs|kubernetes/kubernetes#29961|8/4/16 1:45:23 PM|#10247|Merged

## cadvisor pulls

Description|Upstream PR|Upstream Merge|Origin PR|Status
-----------|-------------|-----------------|----------|------
Make ThinPoolWatcher loglevel consistent|google/cadvisor#1359|7/28/16 12:56:08 PM|#10247|Merged
make sure we only use thin_ls on kernels that have the fix to prevent thinpool corruption|google/cadvisor#1411|8/4/16 4:20:09 PM|#10227|Merged

**Comment by kargakis** [comment]
Add MinReadySeconds to rolling updater: https://github.com/kubernetes/kubernetes/pull/28111

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/29063 for node controller allocation changes?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/29152 for GCE metadata query hang

**Comment by ncdc** [comment]
https://github.com/kubernetes/kubernetes/pull/29246 to fix a regression in image GC / pruning introduced with the switch from go-dockerclient to engine-api

**Comment by kargakis** [comment]
For replica sets:
https://github.com/kubernetes/kubernetes/pull/24733
https://github.com/kubernetes/kubernetes/pull/29183

**Comment by ncdc** [comment]
Fix httpclient setup for gcp credential provider to have timeout: https://github.com/kubernetes/kubernetes/pull/28539

Do not query the metadata server to find out if running on GCE. Retry metadata server query for gcr if running on gce. https://github.com/kubernetes/kubernetes/pull/28871

**Comment by derekwaynecarr** [comment]
For quota on nodeports:
https://github.com/kubernetes/kubernetes/pull/29457

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/29560 fixes using the same configmap in multiple volumes

**Comment by pmorie** [comment]
kubernetes/kubernetes#29673 fixes mount collision issues and timeouts for all non-attachable volumes

**Comment by smarterclayton** [comment]
Let's go ahead and cherry pick (once baseline review is done) to
unblock the merge queue

**Comment by ncdc** [comment]
https://github.com/google/cadvisor/pull/1359

**Comment by ncdc** [comment]
@smarterclayton what do you mean by baseline review?

**Comment by smarterclayton** [comment]
No sudden surprises from upstream after we merge?

**Comment by pmorie** [comment]
Full list of what's needed for storage:

kubernetes/kubernetes#29077 - fix PVC volume not detached if pod deleted via namespace deletion
kubernetes/kubernetes#28048 - disable flaky PD test
kubernetes/kubernetes#28090 - mark 'RW PD, remove it, then schedule' test disabled
kubernetes/kubernetes#28181 - add two pd test with default grace period
kubernetes/kubernetes#28404 - move ungraceful PD tests out of flaky
kubernetes/kubernetes#29031 - wait for PD detach on PD E2E to prevent kernel error
kubernetes/kubernetes#29240 - pass nodeName to VolumeManager instead of hostName
kubernetes/kubernetes#24385 - golint fixes for AWS cloudprovider
kubernetes/kubernetes#28583 - Add spec.Name to the configmap GetVolumeName
kubernetes/kubernetes#24797 - Add enhanced volume and mount logging for block devices
kubernetes/kubernetes#28153 - Fix goroutine map race on Wait()
kubernetes/kubernetes#28409 - Reorganize volume controllers and manager
kubernetes/kubernetes#28939 - Allow mounts to run in parallel for non-attachable volumes
kubernetes/kubernetes#29461 - Fix wrapped volume race
kubernetes/kubernetes#29673 - Fix mount collision timeout issue

**Comment by pmorie** [comment]
kubernetes/kubernetes#29171 is needed to make downward API for pod IP work when using a network plugin.

**Comment by pweil-** [comment]
https://github.com/kubernetes/kubernetes/pull/30021 fixes https://github.com/openshift/origin/issues/9739 (pick waiting upstream approval in https://github.com/openshift/origin/pull/10191)

**Comment by deads2k** [comment]
> For replica sets:
> kubernetes/kubernetes#24733
> kubernetes/kubernetes#29183

These can be removed from the pick list.  Without cohabitation, we can defer the need for conversions between RC and RS.  RS is still in a beta version and we have both controllers running.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/29961 for supplemental GIDs on PVs

**Comment by smarterclayton** [comment]
kubernetes/kubernetes#29655 for pet sets

**Comment by ncdc** [comment]
google/cadvisor#1411 to make sure we only use thin_ls on kernels that have the fix to prevent thinpool corruption

**Comment by ncdc** [comment]
^^^^^^^^^^ everything above this list is in the description or has already merged to origin

**Comment by derekwaynecarr** [comment]
https://github.com/google/cadvisor/pull/1380 to fix working set memory stats calculation.  failure to have this PR would make memory available under report memory pressure.  we also need to document that memory-based eviction is ONLY functional if swap is disabled (see https://github.com/kubernetes/kubernetes/issues/28619#issuecomment-232844073)

**Comment by derekwaynecarr** [comment]
https://github.com/google/cadvisor/pull/1395 -- filesystem usage stats are incorrect in v2 api.

**Comment by derekwaynecarr** [comment]
https://github.com/kubernetes/kubernetes/pull/30386 -- do not allow negative pvc requests.storage

**Comment by smarterclayton** [comment]
I think we want https://github.com/kubernetes/kubernetes/pull/30277 if it merges in the next day or so.  I see this in my profiles as well, and it's low risk.

**Comment by ncdc** [comment]
Fix default resource limits for downward api volumes https://github.com/kubernetes/kubernetes/pull/29639

**Comment by ncdc** [comment]
Exclude Docker devicemapper mounts from fs info https://github.com/google/cadvisor/pull/1358

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/pull/30839 deltafifo usage can cause `fatal error: concurrent map writes`

**Comment by timothysc** [comment]
@deads2k That is likely related to a weird issues we are seeing. 

/cc @mffiedler

**Comment by deads2k** [comment]
> @deads2k That is likely related to a weird issues we are seeing.

Yeah, thanks for the tip off on that.

**Comment by timothysc** [comment]
I ran a report from our sha that @ncdc sent against the head of upstream looking for `panic|crash|race`  results are here: 
https://paste.fedoraproject.org/410461/71550994/

We stumbled upon a crash in testing, my guess is there are more.

**Comment by ncdc** [comment]
I will review Tim's report tonight starting around 8:30pm EDT. I'll do as much as I can to determine what we need to pick, start doing picks, and then handoff to Europe when I am done for the night.

**Comment by eparis** [comment]
This comment is everything from Tim's list just trying to make it easier to go through.  I'm going to edit the comment with links to each PR

- [ ] https://github.com/kubernetes/kubernetes/commit/64af5b074e9b085338285aa6e08dc203951cd825 Merge pull request #29594 from xiang90/fix_panic
- [ ] https://github.com/kubernetes/kubernetes/commit/b15219034d19c285fbc5be26d6f4b59d60191ac3 Prevent panic in 'kubectl exec' when redirecting stdout
- [ ] https://github.com/kubernetes/kubernetes/commit/9a02bffe6d293d26167fd88561f199eb8f62702c Update acquire to use newer JitterUntil vs. sleep with 0 timer which may have caused a race in Until.
- [ ] https://github.com/kubernetes/kubernetes/commit/9fab05fe59fb4e02deb0f839ae2ae79954bbda4c Merge pull request #29743 from timothysc/wait_race_fix
- [ ] https://github.com/kubernetes/kubernetes/commit/842f15c3c62a510f3b1718bf1f086b8951533999 Fix race condition found in JitterUntil.
- [ ] https://github.com/kubernetes/kubernetes/commit/5c6c8eb9a61ef79f376b4a0b85ee3851944edf66 Merge pull request #29531 from AdoHe/rolling_update_panic
- [ ] https://github.com/kubernetes/kubernetes/commit/e86b3f266c67fe2576389439a47d891b72ea121c Merge pull request #29641 from ivan4th/fix-configmap-race
- [ ] https://github.com/kubernetes/kubernetes/commit/a9d631665e34fc604277c4c6fdff13dcbe4e3b3f Add handling empty index key that may cause panic issue
- [ ] https://github.com/kubernetes/kubernetes/commit/df1e925143daf34199b55ffb91d0598244888cce Fix wrapped volume race
- [ ] https://github.com/kubernetes/kubernetes/commit/0949e08336b2225e8826c34d9a455a17eabdec3c fix kubectl rolling update empty file cause panic issue
- [ ] https://github.com/kubernetes/kubernetes/commit/ed3a29bd6aeb9874db4479e00fd2644176f01798 Merge pull request #29581 from Random-Liu/panic-if-cadvisor-not-started
- [ ] https://github.com/kubernetes/kubernetes/commit/0f4e54e52959ca3cc25d498352d53500e27082ca Merge pull request #29124 from aveshagarwal/master-node-e2e-kubelet-metrics-selinux-panic
- [ ] https://github.com/kubernetes/kubernetes/commit/f37d8fd60f93fe5da3bb0a9daec4fe3accaf00e5 Fix node e2e (kubelet metrics) by adding GinkgoRecover to a goroutine to avoid panic
- [ ] https://github.com/kubernetes/kubernetes/commit/450a71cd2ac371143f8ef4d79ac9659387feef8a Merge pull request #29093 from wojtek-t/fix_scheduler_crash
- [ ] https://github.com/kubernetes/kubernetes/commit/78101ac55ecc1b290fc406e1cbdf54bb76851f21 Fix crashes in schedulercache
- [ ] https://github.com/kubernetes/kubernetes/commit/aebc35a9e834fc5828582b58006ebe949a4d9a47 Merge pull request #28800 from lavalamp/reallypanic
- [ ] https://github.com/kubernetes/kubernetes/commit/a8d394bfd43039ac09b7e23b3c2996fd935a9a4c Don't panic if we hit a dangling symlink in mungedocs
- [ ] https://github.com/kubernetes/kubernetes/commit/78c02cd05238c453aab5f244d7034e776281fd77 Stop eating panics
- [ ] https://github.com/kubernetes/kubernetes/commit/afba11e11ea77126d40162a77e0141cb6b446470 Merge pull request #28744 from smarterclayton/fix_fifo_race
- [ ] https://github.com/kubernetes/kubernetes/commit/6462f8224369657a95fd349be67df09343a9e8c4 Merge pull request #28697 from Random-Liu/fix-kube-proxy-panic
- [ ] https://github.com/kubernetes/kubernetes/commit/424685321191af4f3b9c3fe88581f454448718a4 Prevent kube-proxy from panicing when sysfs is mounted as read-only. Send a node event when this happens and hint to the administrator about the remediation.
- [ ] https://github.com/kubernetes/kubernetes/commit/02e29a98b88bb36b2c9f0b4bc83cd33d73e96aa6 reverted the code from 23688 that cause race condition with older version of Go
- [ ] https://github.com/kubernetes/kubernetes/commit/a58b4cf59df732d432ae10a39647f843e26b6d9b Don't panic in NodeController if pod update fails
- [ ] https://github.com/kubernetes/kubernetes/commit/06082b1bdf4c9ff93e5acf33da49f0b091a47d3e Fixed goroutinemap race on Wait()
- [ ] https://github.com/kubernetes/kubernetes/commit/e0b8595f92ef8f1f82f6983f4e6cb20e579a9020 Merge pull request #25255 from ingvagabund/e2e-framework-util-StartPods-panic-for-zero-replicas
- [ ] https://github.com/kubernetes/kubernetes/commit/de1719ed87bbeb75feed5205b15d1ccea09b8dc5 Merge pull request #27831 from quinton-hoole/2016-06-21-fix-panic-in-dns-zone-creation
- [ ] https://github.com/kubernetes/kubernetes/commit/8bc4e9bc136a2c175035da5d54f6a4d0298e93b0 Merge pull request #27435 from wojtek-t/fix_delta_fifo_race
- [ ] https://github.com/kubernetes/kubernetes/commit/5d702a32c14a764397d9d1dd96ed4e994b47072d Fix race in informer
- [ ] https://github.com/kubernetes/kubernetes/commit/80d1ae764288ec163bd11dbbf109aa3c4d7327be Fix panic in TestUnschedulableNodes
- [ ] https://github.com/kubernetes/kubernetes/commit/335da9b125539a11afeb02ddc61c37e9b722ec89 Merge pull request #26410 from jsafrane/fix-test-race
- [ ] https://github.com/kubernetes/kubernetes/commit/903821354e8b9c14a4991a729dcbe9a04b520bde Merge pull request #26642 from wojtek-t/fix_kubelet_test_panics
- [ ] https://github.com/kubernetes/kubernetes/commit/13b57f8ffb6a395541ba7fb5b2b80b798ada6b87 Fix panic in kubelet test
- [ ] https://github.com/kubernetes/kubernetes/commit/ee74cc4354d3201b6095fec805e5c5a95700a54f Fix fake event recorder race
- [ ] https://github.com/kubernetes/kubernetes/commit/2d43e4549e76ab1444f6febbecdd159d3dc0c40b Fix data race in volume controller unit test.
- [ ] https://github.com/kubernetes/kubernetes/commit/d002cb1d634fe2a305d10abfef938f309895a9a2 Fix apiservers crashes
- [ ] https://github.com/kubernetes/kubernetes/commit/1d40f471b4c4e9a7da9616cabfbc7727a022ad19 rkt: Fix docker auth config save directory to avoid race.
- [ ] https://github.com/kubernetes/kubernetes/commit/d00dec782536349716a79ed59a7f4be904d62de4 Merge pull request #26397 from euank/fixReadOnlyRootfsPanic
- [ ] https://github.com/kubernetes/kubernetes/commit/7e0b9bfa66b7aeebfc8a18feb0d82dffe96a85c0 kubenet: Fix panic when teardown run before setup
- [ ] https://github.com/kubernetes/kubernetes/commit/071cfe608640a1808c16f85ef1b7a42b556fb570 Merge pull request #26407 from saad-ali/fixRaceReconcilerTest
- [ ] https://github.com/kubernetes/kubernetes/commit/3c345abafd024853d8ff0fb332db6076cfc610c5 Fix DATA RACE in unit tests: reconciler_test.go
- [ ] https://github.com/kubernetes/kubernetes/commit/ecfd8f723f00068a66778f4819d30eedac532395 rkt: Fix panic in setting ReadOnlyRootFS
- [ ] https://github.com/kubernetes/kubernetes/commit/f79998a9b1592b8872e3bead9b8d59918274bb1a Fix panic when the namespace flag is not present
- [ ] https://github.com/kubernetes/kubernetes/commit/22649a19d01a2eecfd0ab846fac5bb6a037bbb0e Fix panic in auth test failure
- [ ] https://github.com/kubernetes/kubernetes/commit/b7a31ad2615524cefcb82ed4b3832e2105147410 Merge pull request #25690 from fabianofranz/fixes_panic_on_roundtripper_when_tls_under_proxy
- [ ] https://github.com/kubernetes/kubernetes/commit/5940040c96d49f5c894d1117ebea572fea73110a Fixes panic on round tripper when TLS under a proxy
- [ ] https://github.com/kubernetes/kubernetes/commit/a167a6b4df92a6a61c4a9c3e37b7b0f7ef6e0dd6 Merge pull request #25308 from AdoHe/deployment_panic
- [ ] https://github.com/kubernetes/kubernetes/commit/d1480cd8dfe9edc5109d6825b9df67ef96af9079 fix rollout nil panice issue

**Comment by timothysc** [comment]
might want to add ```lock``` to that query

**Comment by ingvagabund** [comment]
With respect to the origin master HEAD (e5178ecf398e8e568ed83fdfdfed5c9d483276c1):

- [ ] ~~https://github.com/kubernetes/kubernetes/pull/28153 https://github.com/kubernetes/kubernetes/commit/06082b1bdf4c9ff93e5acf33da49f0b091a47d3e Fixed goroutinemap race on Wait()~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/25255 https://github.com/kubernetes/kubernetes/commit/e0b8595f92ef8f1f82f6983f4e6cb20e579a9020 Merge pull request #25255 from ingvagabund/e2e-framework-util-StartPods-panic-for-zero-replicas~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/27831 https://github.com/kubernetes/kubernetes/commit/de1719ed87bbeb75feed5205b15d1ccea09b8dc5 Merge pull request #27831 from quinton-hoole/2016-06-21-fix-panic-in-dns-zone-creation~~ {federation not in origin}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/27435 https://github.com/kubernetes/kubernetes/commit/8bc4e9bc136a2c175035da5d54f6a4d0298e93b0 Merge pull request #27435 from wojtek-t/fix_delta_fifo_race~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/27341 https://github.com/kubernetes/kubernetes/commit/5d702a32c14a764397d9d1dd96ed4e994b47072d Fix race in informer~~ {already cherry picked in origin master}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/37345 https://github.com/kubernetes/kubernetes/commit/80d1ae764288ec163bd11dbbf109aa3c4d7327be Fix panic in TestUnschedulableNodes~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26410 https://github.com/kubernetes/kubernetes/commit/335da9b125539a11afeb02ddc61c37e9b722ec89 Merge pull request #26410 from jsafrane/fix-test-race~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26410 https://github.com/kubernetes/kubernetes/commit/2d43e4549e76ab1444f6febbecdd159d3dc0c40b Fix data race in volume controller unit test.~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26642 https://github.com/kubernetes/kubernetes/commit/903821354e8b9c14a4991a729dcbe9a04b520bde Merge pull request #26642 from wojtek-t/fix_kubelet_test_panics~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26642 https://github.com/kubernetes/kubernetes/commit/13b57f8ffb6a395541ba7fb5b2b80b798ada6b87 Fix panic in kubelet test~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26619 https://github.com/kubernetes/kubernetes/commit/ee74cc4354d3201b6095fec805e5c5a95700a54f Fix fake event recorder race~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26564 https://github.com/kubernetes/kubernetes/commit/d002cb1d634fe2a305d10abfef938f309895a9a2 Fix apiservers crashes~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26177 https://github.com/kubernetes/kubernetes/commit/1d40f471b4c4e9a7da9616cabfbc7727a022ad19 rkt: Fix docker auth config save directory to avoid race.~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26397 https://github.com/kubernetes/kubernetes/commit/d00dec782536349716a79ed59a7f4be904d62de4 Merge pull request #26397 from euank/fixReadOnlyRootfsPanic~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26397 https://github.com/kubernetes/kubernetes/commit/ecfd8f723f00068a66778f4819d30eedac532395 rkt: Fix panic in setting ReadOnlyRootFS~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26398 https://github.com/kubernetes/kubernetes/commit/7e0b9bfa66b7aeebfc8a18feb0d82dffe96a85c0 kubenet: Fix panic when teardown run before setup~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26407 https://github.com/kubernetes/kubernetes/commit/071cfe608640a1808c16f85ef1b7a42b556fb570 Merge pull request #26407 from saad-ali/fixRaceReconcilerTest~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26407 https://github.com/kubernetes/kubernetes/commit/3c345abafd024853d8ff0fb332db6076cfc610c5 Fix DATA RACE in unit tests: reconciler_test.go~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26078 https://github.com/kubernetes/kubernetes/commit/f79998a9b1592b8872e3bead9b8d59918274bb1a Fix panic when the namespace flag is not present~~ {already cherry-picked in rebase}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/26025 https://github.com/kubernetes/kubernetes/commit/22649a19d01a2eecfd0ab846fac5bb6a037bbb0e Fix panic in auth test failure~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/25690 https://github.com/kubernetes/kubernetes/commit/b7a31ad2615524cefcb82ed4b3832e2105147410 Merge pull request #25690 from fabianofranz/fixes_panic_on_roundtripper_when_tls_under_proxy~~ {already cherry-picked}
- [ ] ~~https://github.com/kubernetes/kubernetes/pull/25690 https://github.com/kubernetes/kubernetes/commit/5940040c96d49f5c894d1117ebea572fea73110a Fixes panic on round tripper when TLS under a proxy~~ {the same as the one above}
- [X] https://github.com/kubernetes/kubernetes/pull/25308 https://github.com/kubernetes/kubernetes/commit/a167a6b4df92a6a61c4a9c3e37b7b0f7ef6e0dd6 Merge pull request #25308 from AdoHe/deployment_panic {simple cherry-pick, fixed panic}
- [X] https://github.com/kubernetes/kubernetes/pull/25308 https://github.com/kubernetes/kubernetes/commit/d1480cd8dfe9edc5109d6825b9df67ef96af9079 fix rollout nil panice issue {the same as the one above}

**Comment by kargakis** [comment]
Maybe https://github.com/kubernetes/kubernetes/pull/30998 ?

**Comment by liggitt** [comment]
> Maybe kubernetes/kubernetes#30998?

no

**Comment by deads2k** [comment]
> Maybe kubernetes/kubernetes#30998?
> no

How about: "no, that's probably not the correct fix to the problem".

**Comment by ncdc** [comment]
I'm going to close this. Everything listed that needed to be cherry picked has already been picked.
